Added Feature
dmytropogribnyy/chill-out-app pull request #2
Opened 2020-06-16 09:40 UTC by dmytropogribnyy

Please check out a new feature and help me to resolve a problem with the JS file. Thanks a lot!

2020-06-18 07:41 UTC, lazyd3v requested changes

2020-06-18 07:41 UTC, lazyd3v commented on script.js
> +const pointer_container = document.getElementById("pointer-container");
В Javascript для названия переменных принято использовать camel case (должно быть pointerContainer)

2020-06-18 07:41 UTC, lazyd3v commented on script.js
> +const startbtn = document.getElementsById("startbtn");
getElementById (без s)

2020-06-18 07:41 UTC, lazyd3v commented on script.js
> +	pointer_container.style.animationPlayState = "paused";
Отсутствует операция паузы анимации самого кружа

2020-06-18 07:41 UTC, lazyd3v commented on script.js
В этом файле, ниже, стоит вызов setInterval. При нажатии на паузу, этот setInterval не сбрасывается, а должен, иначе при нажатии на паузу текст продолжает меняться

2020-06-18 07:41 UTC, lazyd3v commented on style.css
> +.btn-group {
Нужно добавить z-index или переместить кнопки, потому что круг иногда перекрывает кнопки и ими невозможно пользоваться

2020-06-19 15:50 UTC, lazyd3v requested changes

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +// breathAnimation();
Комментированный код лучше убрать

2020-06-19 15:50 UTC, lazyd3v commented on index.html
> +				onclick="animationStart()"
onclick="animationStart()" нужно убрать, потому что в script.js у нас и так есть вызов addEventListener

2020-06-19 15:50 UTC, lazyd3v commented on index.html
> +				onclick="animationStop()"
Аналогично комментарию выше

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +pointerContainer.style.animationPlayState = "paused";
У нас есть два анимируемых элемента - container и pointerContainer. Необходимо проставить animation="none" обоим элементам

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	setTimeout(() => {
setTimeout для работы с анимацией нужно убрать, в нашем случае в этом нет необходимости, извиняюсь за введение в заблуждение

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	// pointerContainer.style.animationPlayState = "running";
здесь нам нужно включить анимацию

```
container.style.animation = "";
pointerContainer.style.animation = "";
```

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	pointerContainer.style.animation = "none";
Здесь нам нужно приостановить анимацию 

```
container.style.animation = "none";
pointerContainer.style.animation = "none";
```

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	if (animationStart) {
Для чего здесь if? animationStart - это функция, поэтому это условие всегда будет валидно

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +const startbtn = document.querySelector("startbtn");
Должно быть `document.querySelector("#startbtn")` или `document.getElementById("startbtn")`, иначе это не работает

2020-06-19 15:50 UTC, lazyd3v commented on index.html
> +git checkout
```
git checkout
<main></main>
```
стоит убрать

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	pointerContainer.style.animation = "none";
Предлагаю не использовать animationPlayState paused, так как приостанавливать анимацию текста внутри кружка и продолжать ее с момента остановки сложно. Чего не скажешь об остановке анимации и воспроизведения ее с самого начала

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +	setInterval(breathAnimation, totalTime);
`setInterval(breathAnimation, totalTime);` должен вызываться не внутри функции breathAnimation, а по нажатию на кнопку start

2020-06-19 15:50 UTC, lazyd3v commented on script.js
> +pointerContainer.style.animationPlayState = "paused";
```
container.style.animation = "none";
pointerContainer.style.animation = "none"
```

2020-06-19 16:26 UTC, dmytropogribnyy commented on index.html
> +				onclick="animationStop()"
done!

2020-06-19 16:26 UTC, dmytropogribnyy commented on index.html
> +				onclick="animationStart()"
done!

2020-06-19 16:26 UTC, dmytropogribnyy commented on script.js
> +// breathAnimation();
done!

2020-06-19 16:26 UTC, dmytropogribnyy commented on script.js
> +pointerContainer.style.animationPlayState = "paused";
done!
function animationStop() {
	container.style.animation = "none";
	pointerContainer.style.animation = "none";
	clearInterval(breathAnimation);
}

2020-06-19 16:27 UTC, dmytropogribnyy commented on script.js
> +	setTimeout(() => {
done!

2020-06-19 16:28 UTC, dmytropogribnyy commented on script.js
> +	// pointerContainer.style.animationPlayState = "running";
done!

2020-06-19 16:29 UTC, dmytropogribnyy commented on script.js
> +	pointerContainer.style.animation = "none";
done!

2020-06-19 16:29 UTC, dmytropogribnyy commented on script.js
> +	if (animationStart) {
done!

2020-06-19 16:29 UTC, dmytropogribnyy commented on script.js
> +const startbtn = document.querySelector("startbtn");
done!

2020-06-19 16:30 UTC, dmytropogribnyy commented on index.html
> +git checkout
done!

2020-06-19 16:55 UTC, dmytropogribnyy commented on script.js
> +	setInterval(breathAnimation, totalTime);
#done!

startbtn.addEventListener("click", animationStart);

function animationStart() {
	container.style.animation = "";
	pointerContainer.style.animation = "";
	breathAnimation();
	setInterval(breathAnimation, totalTime);
}

2020-06-21 09:25 UTC, lazyd3v requested changes

2020-06-21 09:25 UTC, lazyd3v commented on script.js
> +timeoutId = setTimeout(breathAnimation, totalTime);
Оставь переменные intervalId и timeoutId пустыми

2020-06-21 09:25 UTC, lazyd3v commented on script.js
> +timeoutId = setTimeout(breathAnimation, totalTime);
И само присванивание
```
timeoutId = setTimeout(breathAnimation, totalTime);
```
Не нужно. Смотри комментарий ниже, где нужно было использовать timeoutId

2020-06-21 09:25 UTC, lazyd3v commented on script.js
>  function breathAnimation() {
Я ожидал, что функция breathAnimation будет выглядеть так:

```js
function breathAnimation () {
        text.innerText = "Breathe In";
	container.className = "container grow";
        timeoutId1 = setTimeout(() => {
		text.innerText = "Hold";
		timeoutId2 = setTimeout(() => {
			text.innerText = "Breathe Out";
			container.className = "container shrink";
		}, holdTime);
	}, breathTime);
}
```

И `breathAnimation` уже будет передаваться в setInterval

2020-06-21 09:25 UTC, lazyd3v commented on script.js
> +	intervalId();
```js
intervaId()
timeoutId()
```
вызывают ошибку в консоли, потому что как intervalId так и timeoutId являются числами, а не функциями. Убери эти две строчки :)

2020-06-21 09:25 UTC, lazyd3v commented on script.js
>  function breathAnimation() {
То есть, где-то наверху нужно объявить переменные
```js
let intervalId, timeoutId1, timeoutId2
```
далее по нажатию на кнопку start выполнить
```js
breathAnimation() // это нужно потому, что в первый раз setInterval запускает функцию не сразу, а спустя какое-то время
intervalId = setInterval(breathAnimation, totalTime)
```
а по нажатию на stop
```js
clearInterval(intervalId)
clearTimeout(timeoutId1)
clearTimeout(timeoutId2)
```

2020-06-21 09:56 UTC, lazyd3v requested changes

2020-06-21 09:56 UTC, lazyd3v commented on index.html
> +				onclick="animationStart()"
не исправлено

2020-06-21 09:56 UTC, lazyd3v commented on index.html
> +				onclick="animationStop()"
не исправлено

2020-06-21 09:56 UTC, lazyd3v commented on script.js
> +var breath_out;
в Javascript принято использовать camelCase для названий переменных

2020-06-21 09:56 UTC, lazyd3v commented on script.js
> +	setTimeout(() => {
setTimeout тут не нужен (но то, что внутри нужно)
```
setTimeout(() => {
  pointerContainer.style.animation = "";
}, 150);
```

2020-06-21 09:56 UTC, lazyd3v commented on script.js
> +	if (animationStart) {
не исправлено

2020-06-21 09:56 UTC, lazyd3v commented on script.js
> +pointerContainer.style.animationPlayState = "paused";
Вместо 
```
pointerContainer.style.animationPlayState = "paused";
```
предлагаю использовать
```
pointerContainer.style.animation = "none";
```

для единообразия (как в animationStop)

2020-06-21 09:57 UTC, lazyd3v commented on script.js
> +var breath_out;
И лучше использовать let вместо var, так как он новее

2020-06-21 10:04 UTC, closed without merging